development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:a21556bdbf309b74438d7c69763157ad@tarpon.redistogo.com:11195/
  channel_prefix: ac_warcraft_production
